// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucuzfqhntbyaggzlvrba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjdXpmcWhudGJ5YWdnemx2cmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTU2NzgsImV4cCI6MjA2NTU3MTY3OH0.MiqFJBOlEsSjue_tomT-DOP_hua_bicWv_aeHrDMrGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);